files:
  - source: /sickcore-api/src/main/resources/lang/de_DE.properties
    translation: /sickcore-api/src/main/resources/lang/%locale_with_underscore%.properties
commit_message: "[ci skipped] new translations"
pull_request_labels: 
  - "t: translation"
  - "s: accepted"
pull_request_title: "pull latest crowdin translation changes"
