name: SickCore
version: '${project.version}'
main: me.anton.sickcore.bootstrap.BukkitBootstrap
author: Anton x 4NI0N
description: Core for SickNetwork
api-version: 1.18

softdepends:
  - SimpleCloud-Plugin
  - SimpleCloud-Permission
  - NickAPI
  - HeadDatabase
