name: SickCore
version: 1.0.0
main: net.sickmc.sickcore.core.PaperBootstrap
author: Anton x 4NI0N
description: Core for SickNetwork
api-version: 1.18

libraries:
  - "net.axay:kspigot:1.18.2"
  - "org.litote.kmongo:kmongo-coroutine-serialization:4.6.0"
  - "io.github.crackthecodeabhi:kreds:0.7"
