name: SickCore
version: 1.0.0
main: me.anton.sickcore.core.PaperBootstrap
author: Anton x 4NI0N
description: Core for SickNetwork
api-version: 1.18

softdepends:
  - HeadDatabase

libraries:
  - "net.axay:kspigot:1.18.2"
  - "org.litote.kmongo:kmongo-coroutine-serialization:4.5.1"
  - "io.github.crackthecodeabhi:kreds:0.7"
