package me.anton.sickcore.games.survival.heads;

import lombok.AllArgsConstructor;
import lombok.Getter;
import me.anton.sickcore.games.all.HeadDBAPI;
import me.anton.sickcore.api.utils.common.StringUtils;
import me.anton.sickcore.api.utils.minecraft.bukkit.item.ItemBuilder;
import me.arcaniax.hdb.api.HeadDatabaseAPI;
import org.bukkit.entity.*;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;

@AllArgsConstructor
@Getter
public enum MobHead {

    WANDERINGTRADER(25676, "Wandering Trader Head"),
    ZOMBIEVILLAGER(27597, "Zombie Villager Head"),
    SKELETON_HORSE(6013, "Skeleton Horse Head"),
    ELDERGUARDIAN(25357, "Elder Guardian Head"),
    VINDICATOR(28323, "Vindicator Head"),
    MAGMACUBE(45421, "Magma Cube Head"),
    IRONGOLEM(341, "Iron Golem Head"),
    VILLAGER_NONE(42949, "Villager Head - Professionless"),
    VILLAGER_MASON(32914, "Villager Head - Mason"),
    VILLAGER_CLERIC(28910, "Villager Head - Cleric"),
    VILLAGER_FARMER(32881, "Villager Head - Farmer"),
    VILLAGER_NITWIT(23089, "Villlager Head - Nitwit"),
    VILLAGER_ARMORER(32853, "Villager Head - Armorer"),
    VILLAGER_BUTCHER(32860, "Villager Head - Butcher"),
    VILLAGER_FLETCHER(23759, "Villager Head - Fletcher"),
    VILLAGER_SHEPHERD(32930, "Villager Head - Shepherd"),
    VILLAGER_FISHERMAN(32888, "Villager Head - Fisherman"),
    VILLAGER_LIBRARIAN(32903, "Villager Head - Librarian"),
    VILLAGER_TOOLSMITH(32937, "Villager Head - Toolsmith"),
    VILLAGER_WEAPONSMITH(32944, "Villager Head - Weaponsmith"),
    VILLAGER_CARTOGRAPHER(32867, "Villager Head - Cartographer"),
    VILLAGER_LEATHERWORKER(32902, "Villager Head - Leatherworker"),
    PILLAGER(25149, "Pillager Head"),
    GUARDIAN(3135, "Guardian Head"),
    ENDERMAN(318, "Enderman Head"),
    SNOWMAN(24080, "Snowman Head"),
    SHULKER(38317, "Shulker Head"),
    RAVAGER(28196, "Ravager Head"),
    PHANTOM(41060, "Phantom Head"),
    DROWNED(41025, "Drowned Head"),
    ZOGLIN(36388, "Zoglin Head"),
    WITHER(45024, "Wither Head"),
    TURTLE(17929, "Turtle Head"),
    EVOKER(3862, "Evoker Head"),
    WITCH(35861, "Witch Head"),
    STRAY(22401, "Stray Head"),
    SLIME(22210, "Slime Head"),
    GHAST(321, "Ghast Head"),
    BLAZE(47778, "Blaze Head"),
    HUSK(37860, "Husk Head"),
    VEX(3080, "Vex Head"),
    FOX_RED(26327, "Fox Head - Red"),
    FOX_SNOW(26329, "Fox Head - Snow"),
    BEE(31264, "Bee Head"),
    ACOLOTL_BLUE(46414, "Axolotl Head - Blue"),
    ACOLOTL_GOLD(41590, "Axolotl Head - Gold"),
    ACOLOTL_CYAN(48001, "Axolotl Head - Cyan"),
    ACOLOTL_LUCY(45783, "Axolotl Head - Lucy"),
    ACOLOTL_WILD(41591, "Axolotl Head - Wild"),
    SHEEP_CYAN(3907, "Sheep Head - Cyan"),
    SHEEP_BLUE(3909, "Sheep Head - Blue"),
    SHEEP_MAGENTA(3900, "Sheep Head - Magenta"),
    SHEEP_LIGHT_GRAY(3906, "Sheep Head - Light Gray"),
    SHEEP_LIGHT_BLUE(3916, "Sheep Head - Blue"),
    SHEEP_BLACK(3913, "Sheep Head - Light Blue"),
    SHEEP_GRAY(3905, "Sheep Head - Gray"),
    SHEEP_GREEN(3911, "Sheep Head - Green"),
    SHEEP_RED(3912, "Sheep Head - Red"),
    SHEEP_WHITE(334, "Sheep Head - White"),
    SHEEP_YELLOW(3902, "Sheep Head - Yellow"),
    SHEEP_LIME(3903, "Sheep Head - Lime"),
    SHEEP_PINK(3915, "Sheep Head - Pink"),
    SHEEP_BROWN(3910, "Sheep Head - Brown"),
    SHEEP_ORANGE(3899, "Sheep Head - Orange"),
    SHEEP_PURPLE(3980, "Sheep Head - Purple"),
    BAT(26033, "Bat Head"),
    CAT_WHITE(39024, "Cat Head - White"),
    CAT_RED(38983, "Cat Head - Red"),
    CAT_BLACK(39088, "Cat Head - Black"),
    CAT_TABBY(39040, "Cat Head - Tabby"),
    CAT_CALICO(38905, "Cat Head - Calico"),
    CAT_JELLIE(38968, "Cat Head - Jellie"),
    CAT_PERSIAN(38953, "Cat Head - Persian"),
    CAT_RAGDOLL(39072, "Cat Head - Ragdoll"),
    CAT_SIAMESE(39056, "Cat Head - Siamese"),
    CAT_ALL_BLACK(38933, "Cat Head - All Black"),
    CAT_BRITISH_SHORTHAIR(38921, "Cat Head - British Shorthair"),
    COD(17898, "Cod Head"),
    COW(22866, "Cow Head"),
    PIG(337, "Pig Head"),
    GOAT(42452, "Goat Head"),
    MULE(8918, "Mule Head"),
    WOLF(38471, "Wolf Head"),
    HORSE_WHITE(34340, "Horse Head - White"),
    HORSE_BROWN(14418, "Horse Head - Brown"),
    HORSE_GRAY(43021, "Horse Head - Gray"),
    HORSE_BLACK(34342, "Horse Head - Black"),
    HORSE_CREAMY(34339, "Horse Head - Creamy"),
    HORSE_CHESTNUT(34344, "Horse Head - Chestnut"),
    HORSE_DARK_BROWN(42534, "Horse Head - Dark Brown"),
    LLAMA_CREAMY(26964, "Llama Head - Creamy"),
    LLAMA_GRAY(3930, "Llama Head - Gray"),
    LLAMA_BROWN(3929, "Llama Head - Brown"),
    LLAMA_WHITE(3931, "Llama Head - White"),
    PANDA(23593, "Panda Head"),
    SQUID(338, "Squid Head"),
    DONKEY(38017, "Donkey Head"),
    HOGLIN(34783, "Hoglin Head"),
    OCELOT(47969, "Oxelot Head"),
    PARROT_GRAY(6536, "Parrot Head - Gray"),
    PARROT_RED(39666, "Parrot Head - Red"),
    PARROT_GREEN(25351, "Parrot Head - Green"),
    PARROT_BLUE(6816, "Parrot Head - Blue"),
    PARROT_CYAN(6537, "Parrot Head - Cyan"),
    PIGLIN(34891, "Piglin Head"),
    RABBIT(43626, "Rabbit Head"),
    SALMON(17809, "Salmon Head"),
    SPIDER(32706, "Spider Head"),
    CHICKEN(336, "Chicken Head"),
    DOLPHIN(16799, "Dolphin Head"),
    STRIDER(48214, "Strider Head"),
    ENDERMITE(18427, "Endermite Head"),
    GLOWSQUID(42563, "Glow Squid Head"),
    POLARBEAR(4177, "Polar Bear Head"),
    PUFFERFISH(45707, "Pufferfish Head"),
    SILVERFISH(3936, "Silverfish Head"),
    CAVESPIDER(32707, "Cave Spider Head"),
    MUSHROOMCOW_RED(339, "Mushroom Cow Head - Red"),
    MUSHROOMCOW_BROWN(26552, "Mushroom Cow Head - Brown"),
    PIGLINBRUTE(40777, "Piglin Brute Head"),
    TRADERLLAMA_BROWN(26960, "Trader Llama Head - Brown"),
    TRADERLLAMA_GRAY(26962, "Trader Llama Head - Gray"),
    TRADERLLAMA_WHITE(26961, "Trader Llama Head - White"),
    TRADERLLAMA_CREAMY(26963, "Trader Llama Head - Creamy"),
    TROPICALFISH(30233, "Tropical Fish Head"),
    ZOMBIFIEDPIGLIN(324, "Zombified Piglin Head"),
    SPECIAL_SHEEP(31476, "Ice Sheep - 1/1000");

    public final int id;
    public final String headName;

}
